server:
  port: 8080  # Настройка порта для вашего Spring Boot приложения

management:
  endpoints:
    web:
      exposure:
        include: '*'  # Позволяет открывать все эндпоинты управления
  endpoint:
    prometheus:
      enabled: true  # Включает эндпоинт Prometheus